id: I52A411B5
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T01:01:53.292438'
last_modified: '2022-06-19T01:01:53.292455'
parser: null
source_metadata:
  title: Ritual of sixty torma offerings for Yamāntaka, colophon excerpt
  author: གོང་དཀར་རྡོ་རྗེ་གདན་པ་ཀུན་དགའ་རྣམ་རྒྱལ།
  description: 'Digital version 1.0 {Tibetan}; master xml (completed: 2014-10-29);
    thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Mathias Fermer (mf)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/912
  bases:
    50ba:
      title: Ritual of sixty torma offerings for Yamāntaka, colophon excerpt
      order: 1
      base_file: 50ba.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
